### ISSUE TITLE
Release v0.5.1

### ISSUE THREAD

**Issue by dave42** [mithro/python-datetime-tz#20]
Could you please make a new release of 0.5.1 with the improved Windows timezone handling on PyPi?

**Comment by matthewhampton** [comment]
Hi @mithro,

Any chance you would be able to do this for us?

Thanks!

**Comment by mithro** [comment]
I'll try and do this today. Please keep bugging me until it is done.

Tim 'mithro' Ansell

**Comment by matthewhampton** [comment]
Thanks, @mithro!

**Comment by mithro** [comment]
Released v0.5.2 - https://github.com/mithro/python-datetime-tz/releases/tag/v0.5.2 and https://pypi.python.org/pypi/python-datetime-tz/0.5.2

**Comment by mithro** [comment]
(Also tagged your v0.5.1 version)

**Comment by matthewhampton** [comment]
Thanks, @mithro ...
