### ISSUE TITLE
Cut a release for 0.5.3

### ISSUE THREAD

**Issue by micolous** [mithro/python-datetime-tz#22]
There was a nasty bug introduced in 0.5.2 which prevents the library from being declaring it's dependencies properly (#21).

Cut a new release of the library (0.5.3) which includes this patch, and upload to PyPI.

**Comment by mithro** [comment]
Done. https://pypi.python.org/pypi/python-datetime-tz/0.5.3

**Comment by micolous** [comment]
Thanks :heart:
